### PR TITLE
Fixes #1736

### LINKED ISSUE #1736: PS command causes implant on Darwin to spin the CPU at 100% indefinitely
**Describe the bug**
When SSH is enabled and has at least user logged in via SSH on Mac OS, the `ps` command and other commands that reply on `ps` (e.g. `cursed chrome`) will timeout while spinning the CPU at 100% indefinitely.

**To Reproduce**
1. Enable SSH server on the Mac OS machine.
2. Ensure there is at least one user logged into the machine via SSH.
3. Run implant on this machine.
4. Execute `ps` command from Sliver Console.
5. The RPC call will timeout due to an infinite loop in [implant/sliver/ps/ps_darwin.go#L248]( https://github.com/BishopFox/sliver/blob/85b0e870d05ec47184958dbcb871ddee2eb9e3df/implant/sliver/ps/ps_darwin.go#L248) .
6. Every time a `ps` command is issued under these circumstances, a goroutine is created on the implant stressing the CPU at 100%.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Mac OS 14 Sonoma
 - Reproduced on v1.5.42 and the master branch, assuming the issue exists in all versions based on the change log of ps_darwin.go.

**Additional context**
I further investigated this issue. It turns out the `getArgvFromPid` function is stuck at processes like  `sshd: admin@ttys002`, which only appears when there are users logged into the system via SSH. 

Here's buffer returned from `sysctl` system call. Notice the character between `sshd:` and `admin@ttys002` is a space not NULL.
image

The loop that proceeds the system call expects to parse 3 arguments from the buffer which there are only 2 null-terminated strings in the buffer. The loop would continue looking for the next null-terminated string even though there is none left. It is worth noting that the buffer has a size of `kern.argmax`, which defaults to 1M on my machine. 

To make the problem worse, [at line 251](https://github.com/BishopFox/sliver/blob/7676fc6c37fc33ea17a6ce34784bec1e8107dce6/implant/sliver/ps/ps_darwin.go#L251), the loop continues even when error occurs while reading from the buffer, such as EOF. 

This issue should be an easy fix. Will open a PR in a bit.

### PR DESCRIPTION
**Pull request by lip234**
Fixes issue in the implant where `ps` command leads to infinite loop on Darwin under certain conditions.

### CODE REVIEW

File: implant/sliver/ps/ps_darwin.go [hunk 1]
```diff
@@ -227,12 +227,9 @@ func getArgvFromPid(pid int) ([]string, error) {
...
 		return []string{""}, fmt.Errorf("%s", errStr)
 	}
-	buffer := bytes.NewBuffer(processArgs)
-	numberOfArgs, err := binary.ReadUvarint(buffer)
-	if err != nil {
-		return []string{""}, err
-	}
-	buffer.Next(3)                         // skip  sizeof(int32), the number of args
+	buffer := bytes.NewBuffer(processArgs[0:size])
+	numberOfArgsBytes := buffer.Read(4)
```
Comment (rkervella) [inline implant/sliver/ps/ps_darwin.go:231]: Please fix this call before we can test it. `buffer.Read()` takes a `[]byte` as argument, not an int:

```go
package bytes // import "bytes"

func (b *Buffer) Read(p []byte) (n int, err error)
    Read reads the next len(p) bytes from the buffer or until the buffer is
    drained. The return value n is the number of bytes read. If the buffer has
    no data to return, err is io.EOF (unless len(p) is zero); otherwise it is
    nil.

func (r *Reader) Read(b []byte) (n int, err error)
    Read implements the io.Reader interface.
```

**Review by rkervella — CHANGES_REQUESTED** [review]

File: implant/sliver/ps/ps_darwin.go (hunk 1 above)
Comment (lip234) [reply implant/sliver/ps/ps_darwin.go]: So sorry about the rookie mistake.  It's been fixed. I amended my commit and did a forced push to my branch to keep the commit log clean.

However, I tried to test `sliver-server` but got the follow error. I did run `go generate` on `implant/` which did not change any files. Also removed `~/.sliver` but the issue remains. Any idea where to look at?

```sh
Sliver  Copyright (C) 2022  Bishop Fox
This program comes with ABSOLUTELY NO WARRANTY; for details type 'licenses'.
This is free software, and you are welcome to redistribute it
under certain conditions; type 'licenses' for details.

Unpacking assets ...
panic: runtime error: index out of range [1] with length 1

goroutine 101 [running]:
github.com/bishopfox/sliver/server/rpc.(*Server).GetVersion(0xd5e9630?, {0x2a3a500?, 0x2a914ac?}, 0xf?)
	github.com/bishopfox/sliver/server/rpc/rpc.go:90 +0x13d
github.com/bishopfox/sliver/protobuf/rpcpb._SliverRPC_GetVersion_Handler.func1({0xc023ca8?, 0xc0007ca8a0?}, {0x27c2f80?, 0xc0007ca300?})
	github.com/bishopfox/sliver/protobuf/rpcpb/services_grpc.pb.go:3006 +0xce
github.com/bishopfox/sliver/server/transport.initMiddleware.PayloadUnaryServerInterceptor.func16({0xc023ca8, 0xc0007ca8a0}, {0x27c2f80, 0xc0007ca300}, 0x0?, 0xc00341c348)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/logrus/payload_interceptors.go:29 +0x179
google.golang.org/grpc.getChainUnaryHandler.func1({0xc023ca8, 0xc0007ca8a0}, {0x27c2f80, 0xc0007ca300})
	google.golang.org/grpc@v1.64.0/server.go:1196 +0xb2
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1({0xc023ca8, 0xc0007ca7b0}, {0x27c2f80, 0xc0007ca300}, 0xc00076c100, 0xc000758700)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/logrus/server_interceptors.go:31 +0xfe
google.golang.org/grpc.getChainUnaryHandler.func1({0xc023ca8, 0xc0007ca7b0}, {0x27c2f80, 0xc0007ca300})
	google.golang.org/grpc@v1.64.0/server.go:1196 +0xb2
github.com/grpc-ecosystem/go-grpc-middleware/tags.UnaryServerInterceptor.func1({0xc023ca8?, 0xc0007ca360?}, {0x27c2f80, 0xc0007ca300}, 0xc00076c100, 0xc0007586c0)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/tags/interceptors.go:23 +0x9c
google.golang.org/grpc.getChainUnaryHandler.func1({0xc023ca8, 0xc0007ca360}, {0x27c2f80, 0xc0007ca300})
	google.golang.org/grpc@v1.64.0/server.go:1196 +0xb2
github.com/bishopfox/sliver/server/transport.initMiddleware.auditLogUnaryServerInterceptor.func14({0xc023ca8, 0xc0007ca360}, {0x27c2f80, 0xc0007ca300}, 0xc00076c100, 0xc000758600)
	github.com/bishopfox/sliver/server/transport/middleware.go:317 +0x3e8
google.golang.org/grpc.getChainUnaryHandler.func1({0xc023ca8, 0xc0007ca360}, {0x27c2f80, 0xc0007ca300})
	google.golang.org/grpc@v1.64.0/server.go:1196 +0xb2
github.com/bishopfox/sliver/server/transport.initMiddleware.UnaryServerInterceptor.func13({0xc023ca8?, 0xc0007ca2d0?}, {0x27c2f80, 0xc0007ca300}, 0xc00076c100?, 0xc0007585c0)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/auth/auth.go:47 +0x91
google.golang.org/grpc.NewServer.chainUnaryServerInterceptors.chainUnaryInterceptors.func1({0xc023ca8, 0xc0007ca2d0}, {0x27c2f80, 0xc0007ca300}, 0xc00076c100, 0x80?)
	google.golang.org/grpc@v1.64.0/server.go:1187 +0x85
github.com/bishopfox/sliver/protobuf/rpcpb._SliverRPC_GetVersion_Handler({0x2a3a500, 0xd6c0900}, {0xc023ca8, 0xc0007ca2d0}, 0xc0005ae100, 0xc00023a460)
	github.com/bishopfox/sliver/protobuf/rpcpb/services_grpc.pb.go:3008 +0x143
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000386e00, {0xc023ca8, 0xc0007ca240}, {0xc0347e0, 0xc000002480}, 0xc00343c7e0, 0xc0004e6ff0, 0xd64a0c0, 0x0)
	google.golang.org/grpc@v1.64.0/server.go:1379 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc000386e00, {0xc0347e0, 0xc000002480}, 0xc00343c7e0)
	google.golang.org/grpc@v1.64.0/server.go:1790 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.64.0/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 78
	google.golang.org/grpc@v1.64.0/server.go:1040 +0x125

```

**Review by rkervella — APPROVED** [review]

**Comment by rkervella** [comment]
Thanks for the fix @lip234. Please remember to sign your commits next time.
